# Site settings
author: Irene Scott
title: My Software Engineering Journey with Flatiron School
header-img: img/home-bg.png
email: irenejinscott@gmail.com
copyright_name: Irene Scott
description: > # this means to ignore newlines until "baseurl:"
  Trying my best everyday to get to my goals, no matter how hard
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  codewithirene567

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
